version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code_runner_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-code_runner}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_change_in_production}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - MAX_EXECUTION_TIME=10000
      - MAX_MEMORY=512
    volumes:
      - ./:/app
      - /app/node_modules
      - code_execution:/tmp/code-execution
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code_runner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  code_execution: