services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - JAVA_VERSION=${JAVA_VERSION}
        - CPP_VERSION=${CPP_VERSION}
        - C_VERSION=${C_VERSION}
    container_name: code_runner_api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - code_execution_tmp:/tmp/code-execution
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "mkdir -p /tmp/code-execution && chmod 755 /tmp/code-execution && npm run dev"
    restart: always

  db:
    image: postgres:14
    container_name: code_runner_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  code_execution_tmp:
    driver: local
